apiVersion: v2
name: easyznab
description: Easynews-to-Newznab proxy packaged for Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/benkelly/easyznab
sources:
  - https://github.com/benkelly/easyznab
maintainers:
  - name: Ben Kelly
