{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "easyznab.secretName" . }}
  labels:
    {{- include "easyznab.labels" . | nindent 4 }}
  {{- if .Values.secret.annotations }}
  annotations:
    {{- toYaml .Values.secret.annotations | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  PROXY_API_KEY: {{ .Values.secret.data.PROXY_API_KEY | quote }}
  EASYNEWS_USER: {{ .Values.secret.data.EASYNEWS_USER | quote }}
  EASYNEWS_PASS: {{ .Values.secret.data.EASYNEWS_PASS | quote }}
{{- end }}
